apt-get install -y wget
apt-get install -y curl
apt-get install -y gzip
apt-get install -y gcc
apt-get install -y g++
apt-get install -y libicu-dev
apt-get install -y libbz2-dev
apt-get install -y build-essential
apt-get install -y cmake
apt-get install -y xterm
